jobs:
  include:
    - language: python
      python:
        - "3.5"
        - "3.6"      # current default Python on Travis CI
      # command to install dependencies
      install:
        - pip install git+https://github.com/pmla/evgraf@wallpaper-groups
        - pip install git+https://github.com/pmla/auguste@two-dimensional
      # command to run tests
      script:
        - pytest tests/*
